### PR TITLE
cmd/ach: initial setup of CLI tool to pretty print ACH files, diff and reformat them

### PR DESCRIPTION
**Pull request by adamdecaf**
This prints ACH files in a nicer format like:

```
Describing ACH file 'test/testdata/ppd-debit.ach'
  Origin    OriginName   Destination DestinationName
  121042882 My Bank Name 231380104   Federal Reserve Bank

  BatchNumber Type ServiceClass Addendas TotalDebits TotalCredits
  1           PPD  225          1        100000000   0

    TxCode AccountNumber     Amount    Name                   TraceNumber
    27     12345678          100000000 Receiver Account Name  121042880000001
```
```
Describing ACH file 'test/testdata/return-WEB.ach'
  Origin    OriginName              Destination DestinationName
  691000134 ASF APPLICATION SUPERVI 091400606   FIRST BANK & TRUST

  BatchNumber Type ServiceClass Addendas TotalDebits TotalCredits
  1           WEB  200          2        12354       0

    TxCode AccountNumber     Amount Name                   TraceNumber
    26     123456789         12354  Paul Jones             091000017611242

  BatchNumber Type ServiceClass Addendas TotalDebits TotalCredits
  2           WEB  200          2        0           4565

    TxCode AccountNumber     Amount Name                   TraceNumber
    21     867530999999      4565   Bob Marley             021000029461242
```
```
Describing ACH file 'cmd/readACH/201805101354.ach'
  Origin    OriginName  Destination DestinationName
  121042882 Wells Fargo 231380104   Citadel

  BatchNumber Type ServiceClass Addendas TotalDebits TotalCredits
  1           PPD  200          2500     0           125000000

    TxCode AccountNumber     Amount Name                   TraceNumber
    22     81967038518       100000 Steven Tander          121042880000001
    22     81967038518       100000 Steven Tander          121042880000002
    22     81967038518       100000 Steven Tander          121042880000003
```

### CODE REVIEW

**Comment by adamdecaf** [comment]
I've added two more flags/commands: 

`-diff` for comparing two files: (This would contain colorization in the future)
```
$ ach -diff test/testdata/ppd-debit.ach test/testdata/web-debit.ach 
  Origin    OriginName       Destination DestinationName
- 231380104 Your Company Inc 031300012   Some Bank            
+ 121042882 My Bank Name     231380104   Federal Reserve Bank 
```

`-reformat` for converting between formats (i.e. JSON -> ach) 
```
$ ach -reformat=ach test/testdata/ppd-valid.json 
101 23138010401210428821810081055A094101Citadel                Wells Fargo                    
5200Wells Fargo                         121042882 PPDTrans. Des      2018-1   1121042880000001
62223138010481967038518      0000100000#83738AB#      Steven Tander           0121042880000001
82000000010023138010000000000000000000100000121042882                          121042880000001
9000001000001000000010023138010000000000000000000100000                                       
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
```

**Review by wadearnold — APPROVED** [review]
How do we plan on distributing this tool?

**Comment by adamdecaf** [comment]
We could release it for osx and linux with Homebrew. Also, binaries can be released like the HTTP server on each release.

**Comment by adamdecaf** [comment]
Here's some example output now:

```
$ ach 20200225-121042882-3.ach  | head -n20 
Describing ACH file '20200225-121042882-3.ach'

  Origin     OriginName  Destination  DestinationName  FileCreationDate  FileCreationTime
  121042882  Moov, Inc   121042882    Moov Bank        200225            0835

  BatchCount  BlockCount  EntryAddendaCount  TotalDebitAmount  TotalCreditAmount
  1063        850         6370               52917             67339

  BatchNumber  Type  ServiceClass  Addendas  TotalDebits  TotalCredits
  1            PPD   200           6         72           72

    TxCode  AccountNumber      Amount  Name                    TraceNumber
    32      729971827          33      Elated Minsky           121042887053015
    32      729971827          39      Elated Minsky           121042887053016
    27      729971827          72      Elated Minsky           121042887053017

```

**Comment by adamdecaf** [comment]
After adding support for printing non-IAT addenda records. 

<details>
<summary>Addenda02</summary>

```
$ ach test/ach-mte-read/mte-read.ach 
Describing ACH file 'test/ach-mte-read/mte-read.ach'

  Origin     OriginName    Destination  DestinationName       FileCreationDate  FileCreationTime
  231380104  My Bank Name  031300012    Federal Reserve Bank  181218            0000

  BatchCount  BlockCount  EntryAddendaCount  TotalDebitAmount  TotalCreditAmount
  1           1           2                  10000             0

  BatchNumber  Type  ServiceClass  Addendas  TotalDebits  TotalCredits
  1            MTE   225           2         10000        0

    TxCode  AccountNumber      Amount  Name                    TraceNumber      Category
    27      744-5678-99        10000   JANE DOE                231380100000001  

      Addenda02
      ReferenceInfoOne  ReferenceInfoTwo  TerminalIdentification  TransactionSerial  Date  AuthCodeOrExires  Location                City     State  TraceNumber
                                          200509                  123456             1224                    321 East Market Street  ANYTOWN  VA     231380100000001
```

</details>

<details>
<summary>Addenda05</summary>

```
$ ach test/ach-web-read/web-credit.ach 
Describing ACH file 'test/ach-web-read/web-credit.ach'

  Origin     OriginName    Destination  DestinationName       FileCreationDate  FileCreationTime
  121042882  My Bank Name  231380104    Federal Reserve Bank  181011            0000

  BatchCount  BlockCount  EntryAddendaCount  TotalDebitAmount  TotalCreditAmount
  1           1           4                  0                 10799

  BatchNumber  Type  ServiceClass  Addendas  TotalDebits  TotalCredits
  1            WEB   220           4         0            10799

    TxCode  AccountNumber      Amount  Name                    TraceNumber      Category
    22      12345678           10000   Wade Arnold             121042880000001  

      Addenda05
      PaymentRelatedInformation  SequenceNumber  EntryDetailSequenceNumber
      PAY-GATE payment           1               1

    TxCode  AccountNumber      Amount  Name                    TraceNumber      Category
    22      81967038518        799     Wade Arnold             121042880000002  

      Addenda05
      PaymentRelatedInformation        SequenceNumber  EntryDetailSequenceNumber
      Monthly Membership Subscription  1               2

```

</details>

<details>
<summary>Addenda98</summary>

```
$ ach test/testdata/cor-example.ach 
Describing ACH file 'test/testdata/cor-example.ach'

  Origin     OriginName    Destination  DestinationName       FileCreationDate  FileCreationTime
  121042882  My Bank Name  231380104    Federal Reserve Bank  190829            1236

  BatchCount  BlockCount  EntryAddendaCount  TotalDebitAmount  TotalCreditAmount
  1           1           2                  0                 0

  BatchNumber  Type  ServiceClass  Addendas  TotalDebits  TotalCredits
  1            COR   220           2         0            0

    TxCode  AccountNumber      Amount  Name                    TraceNumber      Category
    21      744-5678-99        0       Best Co. #23            121042880000001  NOC

      Addenda98
      ChangeCode  OriginalTrace    OriginalDFI  CorrectedData  TraceNumber
      C01         121042880000001  12104288     1918171614     091012980000088

```

</details>

<details>
<summary>Addenda99</summary>

```
$ ach test/testdata/return-WEB.ach 
Describing ACH file 'test/testdata/return-WEB.ach'

  Origin     OriginName               Destination  DestinationName     FileCreationDate  FileCreationTime
  691000134  ASF APPLICATION SUPERVI  091400606    FIRST BANK & TRUST  181017            0306

  BatchCount  BlockCount  EntryAddendaCount  TotalDebitAmount  TotalCreditAmount
  2           1           4                  12354             4565

  BatchNumber  Type  ServiceClass  Addendas  TotalDebits  TotalCredits
  1            WEB   200           2         12354        0

    TxCode  AccountNumber      Amount  Name                    TraceNumber      Category
    26      123456789          12354   Paul Jones              091000017611242  Return

      Addenda99
      ReturnCode  OriginalTrace    DateOfDeath  OriginalDFI  AddendaInformation  TraceNumber
      R01         091400600000001               09100001                         091000017611242

  BatchNumber  Type  ServiceClass  Addendas  TotalDebits  TotalCredits
  2            WEB   200           2         0            4565

    TxCode  AccountNumber      Amount  Name                    TraceNumber      Category
    21      867530999999       4565    Bob Marley              021000029461242  Return

      Addenda99
      ReturnCode  OriginalTrace    DateOfDeath  OriginalDFI  AddendaInformation  TraceNumber
      R03         091400600000003               02100002                         021000029461242
```

</details>

**Pull request merged**
