### PR TITLE
use new Travis-CI for windows

### PR DESCRIPTION
**Pull request by adamdecaf**
See: https://blog.travis-ci.com/2018-10-11-windows-early-release

### CODE REVIEW

**Comment by adamdecaf** [comment]
https://travis-ci.community/t/go-lang-support-on-windows/239

**Comment by adamdecaf** [comment]
`goveralls -repotoken $COVERALLS_TOKEN` failed on windows because the env var syntax is `%COVERALLS_TOKEN%`. I like codecov because they don't require a token. Does goveralls require a token for public repos? (codecov only requires it for private repos).

**Review by wadearnold — APPROVED** [review]
Now that ACH has been moved to travis-ci.com this should work. I don't think that it worked on the .org domain.

**Comment by adamdecaf** [comment]
This previously built on windows too.

**Pull request merged**
