### PR TITLE
Go back to old commit in our master

### PR DESCRIPTION
**Pull request by killianbrackey**
Go back to an old commit and build from our original fork

### CODE REVIEW

**Comment by killianbrackey** [comment]
Sorry! Meant to add these changes into our fork

**Comment by wadearnold** [comment]
@killianbrackey anything that I can do to keep your team based off the main branch? Happy to collaborate in anyway to make the library better. Sorry that I broke your build I thought I had a good grasp of tams using the library.

**Comment by killianbrackey** [comment]
@wadearnold Love the tool so far -- we are currently in rapid development and needed to get this into a set place so we could focus on some different areas, but we plan on coming back to your source branch and making what we are doing compatible in master so that we can troubleshoot issues together moving forward.  We are mostly using the WEB format so on reading return files there were a number of validators that were failing and there is one column that needs to be written but is ignored in PPD.

Most notable changes: https://github.com/moov-io/ach/compare/master...sezzle:master#diff-ed6ec976ee948cb81f2bbef47adb704dL48

And the validators below this line:
https://github.com/moov-io/ach/compare/master...sezzle:master#diff-ed6ec976ee948cb81f2bbef47adb704dL189

Again we would be happy to build in support for these but wanted to get things up and running asap.  I'd be happy to help get these integrated, but haven't had the chance to read through all of the source quite yet.

**Comment by wadearnold** [comment]
Sounds great @killianbrackey and I fully understand being under pressure. I wanted an Open Source hardened ACH service for a decade of owning and company. It took and exit and sabbatical to finally getting around to writing one. 

I have some big changes coming to the library to make error reporting much better and easier to add additional SEC types such as web. Wait till this gets merged in before you start digging into the code. 

Errors reporting refactor 
https://github.com/wadearnold/ach/tree/Errors-refactor-for-more-detail-and-wrapping

Strategy for adding more Batch types
https://github.com/moov-io/ach/issues/105

Thanks for giving the library a try!

**Comment by killianbrackey** [comment]
@wadearnold I'll be happy to help out with this where I can.  I am looking at adding CCD along with WEB as SEC codes (the two main use cases we are going to make use of).  I plan on going through all of the source for this project over the next week or so as I take a look at what adding this functionality is going to take.  It looks like you made some good progress in #105 .  I will let you know if I have any questions as I get us back over to your master branch 👍

**Comment by wadearnold** [comment]
Sounds great. I am trying to do one more refactor and add WEB support. I should have that committed before the weekend. CCD/PPD test files would be super helpful. I am happy to get on a hangout with you and walk through the code.

**Pull request closed without merging**
